[versions]
android = "7.0.3"
composeJetbrains = "1.0.0-beta6-dev455"
javierscGradlePlugins = "0.1.0-rc.8"
kotlin = "1.5.31"
kotlinBinaryValidator = "0.8.0"

[libraries]
android-toolsBuild-gradle = { group = "com.android.tools.build", name = "gradle", version.ref = "android" }
javiersc-gradlePlugins-allPluginsX = { module = "com.javiersc.gradle-plugins:all-plugins", version.ref = "javierscGradlePlugins" }
jetbrains-compose-composeGradlePluginX = { module = "org.jetbrains.compose:compose-gradle-plugin", version.ref = "composeJetbrains" }
jetbrains-kotlin-kotlinGradlePluginX = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
jetbrains-kotlinx-binaryCompatibilityValidator = { module = "org.jetbrains.kotlinx:binary-compatibility-validator", version.ref = "kotlinBinaryValidator" }
